# Generated by Django 4.2.4 on 2023-08-05 15:12

import User.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', User.managers.AccountManager()),
            ],
        ),
    ]
