# Generated by Django 4.2.4 on 2023-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_alter_category_title'),
        ('User', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='Article.category'),
        ),
    ]
