# Generated by Django 4.2.4 on 2023-08-06 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Article', '0004_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blocks',
            field=models.ManyToManyField(related_name='blocked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
